version: '3'

services:

  php:
    container_name: php-monte
    build:
      context: ./ops/php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/laravel
      - ./ops/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      APP_ENV: dev
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mysql
    networks:
      - net

  nginx:
    container_name: nginx-monte
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www/laravel
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - net

  mysql:
    container_name: mysql-monte
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    volumes:
      - ./ops/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - net

networks:
  net:

